### PR TITLE
add package: lighttpd

### PR DESCRIPTION
**Pull request by dbat**

### CODE REVIEW

**Comment by gstrauss** [comment]
Why build lighttpd without pcre, without ipv6, and without large file support?
```
+	--without-pcre \
+	--without-pcre \
+	--disable-ipv6 \
+	--disable-lfs \
```

**Comment by dbat** [comment]
ipv6: inet6 is not enable in the kernel itself, see: src/sys/mips/conf/std.AR934X
LFS: I highly doubt it will process >4G files, serving 4K movies?
pcre: it supposed to be enabled, maybe I missed it (pcre wasn't successfully built beforewise)
But anyway all of them are in order to gain reduced size, we'll sure enabled them when possible.

**Comment by gstrauss** [comment]
* makes sense to avoid ipv6 if not enabled in kernel
* reasonable to build without LFS if there is no chance storage will be extended, e.g. via USB, where large files might exist.
* However, building without PCRE substantially reduces the flexibility of user-controlled lighttpd configuration, so I highly recommend building with PCRE unless not possible to do so.

FYI: the next version of lighttpd will move openssl code into a module, and so the memory footprint of lighttpd is reduced when mod_openssl is not loaded.

**Comment by gstrauss** [comment]
> But anyway all of them are in order to gain reduced size, we'll sure enabled them when possible.

BTW, you can compile the lighttpd package with -Os instead of the default -O2 to reduce the .text size of the main lighttpd executable by about 20%

**Comment by dbat** [comment]
OK thanks, good to know

**Pull request merged**
